//TelemetryOnTests

traces
| where tostring(customDimensions.eventId) in ("ALWLD00001","ALWLD00002","ALWLD00003")
| extend
timestamp = timestamp
    , eventId = customDimensions.eventId
    , TestSuiteName_ = tostring(customDimensions.alTestSuiteName)
    , CodeunitId_ = tostring(customDimensions.alCodeunitId)
    , StartTime_ = tostring(customDimensions.alStartTime)
    , EndTime_ = tostring(customDimensions.alEndTime)
    , Result_ = tostring(customDimensions.alResult)
    , NoOfReads_ = tostring(customDimensions.alNoOfReads)
    , NoOfSqlStatements_ = tostring(customDimensions.alNoOfSQLStatements)
    , DurationMs_ = tostring(customDimensions.alDurationMs)
| project
timestamp,
    eventId,
    TestSuiteName_,
    CodeunitId_,
    StartTime_,
    EndTime_,
    Result_,
    NoOfReads_,
    NoOfSqlStatements_,
    DurationMs_

